# Count placeOfActivity
#
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
PREFIX gndo: <http://d-nb.info/standards/elementset/gnd#>
#
select (str(count(distinct ?pm20)) as ?count) ?place
where {
  ?pm20 zbwext:activity/schema:location ?place ;
                       zbwext:freeDocCount ?docCount .
  filter(?docCount > 0)
}
group by ?place
order by desc(count(distinct ?pm20))
